CREATE DATABASE RENTAL
GO

USE RENTAL
GO

CREATE TABLE EMPRESA(
idEmpresa INT IDENTITY PRIMARY KEY,
nomeEmpresa VARCHAR(100)UNIQUE NOT NULL,
enderecoEmp VARCHAR(275)UNIQUE NOT NULL,
telefoneEmp VARCHAR(11) UNIQUE NOT NULL
);
GO

CREATE TABLE MARCA(
idMarca INT IDENTITY PRIMARY KEY,
nomeMarca VARCHAR(75) UNIQUE NOT NULL,
);
GO
 
CREATE TABLE TIPOS_VEICULOS(
idTiposVei INT IDENTITY PRIMARY KEY,
nomeTipo VARCHAR(155)
);

CREATE TABLE MODELO(
idModelo INT IDENTITY PRIMARY KEY,
idMarca INT FOREIGN KEY REFERENCES MARCA(idMarca),
idTipoVei INT FOREIGN KEY REFERENCES TIPO_VEICULOS(idTiposVei),
descModelo VARCHAR(325)
);
GO

CREATE TABLE VEICULOS(
idVeiculos INT IDENTITY PRIMARY KEY,
idEmpresa INT FOREIGN KEY REFERENCES EMPRESA(idEmpresa),
idModelo INT FOREIGN KEY REFERENCES MODELO(idModelo),
placaVei VARCHAR(7) NOT NULL
);
GO

CREATE TABLE CLIENTE(
idCliente INT IDENTITY PRIMARY KEY,
nomeCliente VARCHAR(75) NOT NULL,
sobrenomeCli VARCHAR(75) NOT NULL,
CPF VARCHAR(11) NOT NULL,
telCliente VARCHAR(11) NOT NULL,
emailCliente VARCHAR(275)
);
GO

CREATE TABLE ALUGUEL(
idAluguel INT IDENTITY PRIMARY KEY,
idCliente INT FOREIGN KEY REFERENCES CLIENTE(idCliente),
idVeiculos INT FOREIGN KEY REFERENCES VEICULOS(idVeiculos),
valorAluguel MONEY NOT NULL,
dataInicio DATE NOT NULL,
devolucao DATE NOT NULL
);